//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medimall.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BillDetail
    {
        public int BillDetailId { get; set; }
        [Display(Name = "Mã vận đơn")]
        public Nullable<int> BillId { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public Nullable<int> ProductId { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Giá")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "Mã giảm giá")]
        public Nullable<int> VoucherId { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> Total { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Product Product { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
