//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medimall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int BillId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Phone { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
