//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medimall.Models
{
    using Medimall.Helper;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.ListDrugs = new HashSet<ListDrug>();
        }

        [Display(Name = "Mã sản phẩm")]
        public int ProductId { get; set; }
        [Display(Name = "Mã danh mục")]
        public string CategoryId { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Tên sản phẩm")]
        public string ProductName { get; set; }
        [Display(Name = "Hình ảnh")]
        public string ProductImg { get; set; }
        [Display(Name = "Công dụng")]
        public string UsesFor { get; set; }
        [Display(Name = "Thành phần")]
        public string Ingredient { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Đơn giá")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Số lượng đã bán")]
        public Nullable<int> QuantitySold { get; set; }
        [Display(Name = "Dành cho covid")]
        public Nullable<bool> IsForCovid { get; set; }

        [Display(Name = "Picture")]
        [NotMapped]
        [ValidateFile]
        public HttpPostedFileBase Photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListDrug> ListDrugs { get; set; }
    }
}