//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medimall.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }

        public int VoucherId { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Mã voucher")]
        public string VoucherCode { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Phần trăm khuyến mãi")]
        public Nullable<int> Percent { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [Display(Name = "Nội dung")]
        public string VoucherDetail { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
        public int AccountId { get; set; }
        [Display(Name = "Áp dụng từ")]
        public Nullable<decimal> StartFrom { get; set; }

        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
    }
}
